### YamlMime:ManagedReference
items:
- uid: FlowerProject.Settings.returnPressedAction
  commentId: T:FlowerProject.Settings.returnPressedAction
  id: Settings.returnPressedAction
  parent: FlowerProject
  children: []
  langs:
  - csharp
  - vb
  name: Settings.returnPressedAction
  nameWithType: Settings.returnPressedAction
  fullName: FlowerProject.Settings.returnPressedAction
  type: Delegate
  source:
    remote:
      path: Assets/Scripts/Managers/Settings.cs
      branch: main
      repo: https://github.com/mrobinson-ad/MYG-Project-3.git
    id: returnPressedAction
    path: ../Assets/Scripts/Managers/Settings.cs
    startLine: 18
  assemblies:
  - FlowerProject
  namespace: FlowerProject
  syntax:
    content: public delegate void Settings.returnPressedAction(UIDocument scene)
    parameters:
    - id: scene
      type: UnityEngine.UIElements.UIDocument
    content.vb: Public Delegate Sub Settings.returnPressedAction(scene As UIDocument)
references:
- uid: FlowerProject
  commentId: N:FlowerProject
  href: FlowerProject.html
  name: FlowerProject
  nameWithType: FlowerProject
  fullName: FlowerProject
- uid: UnityEngine.UIElements.UIDocument
  commentId: T:UnityEngine.UIElements.UIDocument
  parent: UnityEngine.UIElements
  isExternal: true
  name: UIDocument
  nameWithType: UIDocument
  fullName: UnityEngine.UIElements.UIDocument
- uid: UnityEngine.UIElements
  commentId: N:UnityEngine.UIElements
  isExternal: true
  name: UnityEngine.UIElements
  nameWithType: UnityEngine.UIElements
  fullName: UnityEngine.UIElements
  spec.csharp:
  - uid: UnityEngine
    name: UnityEngine
    isExternal: true
  - name: .
  - uid: UnityEngine.UIElements
    name: UIElements
    isExternal: true
  spec.vb:
  - uid: UnityEngine
    name: UnityEngine
    isExternal: true
  - name: .
  - uid: UnityEngine.UIElements
    name: UIElements
    isExternal: true
