### YamlMime:ManagedReference
items:
- uid: FlowerProject.Settings.volumeChangeAction
  commentId: T:FlowerProject.Settings.volumeChangeAction
  id: Settings.volumeChangeAction
  parent: FlowerProject
  children: []
  langs:
  - csharp
  - vb
  name: Settings.volumeChangeAction
  nameWithType: Settings.volumeChangeAction
  fullName: FlowerProject.Settings.volumeChangeAction
  type: Delegate
  source:
    remote:
      path: Assets/Scripts/Managers/Settings.cs
      branch: main
      repo: https://github.com/mrobinson-ad/MYG-Project-3.git
    id: volumeChangeAction
    path: ../Assets/Scripts/Managers/Settings.cs
    startLine: 12
  assemblies:
  - FlowerProject
  namespace: FlowerProject
  syntax:
    content: public delegate void Settings.volumeChangeAction(VisualElement target, float volume)
    parameters:
    - id: target
      type: UnityEngine.UIElements.VisualElement
    - id: volume
      type: System.Single
    content.vb: Public Delegate Sub Settings.volumeChangeAction(target As VisualElement, volume As Single)
references:
- uid: FlowerProject
  commentId: N:FlowerProject
  href: FlowerProject.html
  name: FlowerProject
  nameWithType: FlowerProject
  fullName: FlowerProject
- uid: UnityEngine.UIElements.VisualElement
  commentId: T:UnityEngine.UIElements.VisualElement
  parent: UnityEngine.UIElements
  isExternal: true
  name: VisualElement
  nameWithType: VisualElement
  fullName: UnityEngine.UIElements.VisualElement
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: UnityEngine.UIElements
  commentId: N:UnityEngine.UIElements
  isExternal: true
  name: UnityEngine.UIElements
  nameWithType: UnityEngine.UIElements
  fullName: UnityEngine.UIElements
  spec.csharp:
  - uid: UnityEngine
    name: UnityEngine
    isExternal: true
  - name: .
  - uid: UnityEngine.UIElements
    name: UIElements
    isExternal: true
  spec.vb:
  - uid: UnityEngine
    name: UnityEngine
    isExternal: true
  - name: .
  - uid: UnityEngine.UIElements
    name: UIElements
    isExternal: true
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
